In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./datasets/dubai_cold_coffee_spots_clean.csv")

In [3]:
df

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,16:30

In [4]:
df_areas = pd.read_csv("./datasets/dubai_areas.csv")

In [5]:
df_areas

            area_name emoji     lat     lng
0      Downtown Dubai    🏙️  25.200  55.300
1      Jumeirah Beach     🌊  25.205  55.260
2        Business Bay     🏢  25.185  55.310
3           City Walk    🛍️  25.210  55.270
4             Al Safa     🕌  25.175  55.255
5   Sheikh Zayed Road     🌆  25.220  55.290
6                DIFC     🏨  25.215  55.285
7         Zabeel Park     🌳  25.230  55.320
8             Al Wasl     🏫  25.190  55.340
9           Oud Metha     🏪  25.240  55.315
10        Al Jafiliya     🚇  25.245  55.295
11        Al Mankhool    🏘️  25.165  55.305
12            Al Bada     🌴  25.155  55.330
13              Satwa     🏬  25.175  55.275

In [6]:
df_areas["area_label"] = df_areas['emoji'] + " " + df_areas["area_name"]

In [7]:
df_areas

            area_name emoji     lat     lng           area_label
0      Downtown Dubai    🏙️  25.200  55.300    🏙️ Downtown Dubai
1      Jumeirah Beach     🌊  25.205  55.260     🌊 Jumeirah Beach
2        Business Bay     🏢  25.185  55.310       🏢 Business Bay
3           City Walk    🛍️  25.210  55.270         🛍️ City Walk
4             Al Safa     🕌  25.175  55.255            🕌 Al Safa
5   Sheikh Zayed Road     🌆  25.220  55.290  🌆 Sheikh Zayed Road
6                DIFC     🏨  25.215  55.285               🏨 DIFC
7         Zabeel Park     🌳  25.230  55.320        🌳 Zabeel Park
8             Al Wasl     🏫  25.190  55.340            🏫 Al Wasl
9           Oud Metha     🏪  25.240  55.315          🏪 Oud Metha
10        Al Jafiliya     🚇  25.245  55.295        🚇 Al Jafiliya
11        Al Mankhool    🏘️  25.165  55.305       🏘️ Al Mankhool
12            Al Bada     🌴  25.155  55.330            🌴 Al Bada
13              Satwa     🏬  25.175  55.275              🏬 Satwa

In [8]:
df_areas.to_csv("datasets/dubai_areas_with_label.csv")

In [9]:
options = list(df['type'].unique())
options

['cart', 'truck', 'cafe']

In [10]:
options.insert(0,'All')

In [11]:
options

['All', 'cart', 'truck', 'cafe']

In [12]:
a,b,c = [23,56,7]

In [13]:
a

23

In [14]:
b

56

In [15]:
df_areas

            area_name emoji     lat     lng           area_label
0      Downtown Dubai    🏙️  25.200  55.300    🏙️ Downtown Dubai
1      Jumeirah Beach     🌊  25.205  55.260     🌊 Jumeirah Beach
2        Business Bay     🏢  25.185  55.310       🏢 Business Bay
3           City Walk    🛍️  25.210  55.270         🛍️ City Walk
4             Al Safa     🕌  25.175  55.255            🕌 Al Safa
5   Sheikh Zayed Road     🌆  25.220  55.290  🌆 Sheikh Zayed Road
6                DIFC     🏨  25.215  55.285               🏨 DIFC
7         Zabeel Park     🌳  25.230  55.320        🌳 Zabeel Park
8             Al Wasl     🏫  25.190  55.340            🏫 Al Wasl
9           Oud Metha     🏪  25.240  55.315          🏪 Oud Metha
10        Al Jafiliya     🚇  25.245  55.295        🚇 Al Jafiliya
11        Al Mankhool    🏘️  25.165  55.305       🏘️ Al Mankhool
12            Al Bada     🌴  25.155  55.330            🌴 Al Bada
13              Satwa     🏬  25.175  55.275              🏬 Satwa

In [16]:
selected_area = "Al Bada"

In [17]:
values = df_areas[df_areas['area_name'] == selected_area][['lat','lng']].iloc[0]

In [18]:
tuple(values)

(25.155, 55.33)

In [19]:
df

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,16:30

In [20]:
for data in df.iterrows():
    row = data[1]
    lat = row['lat']
    lng = row['lng']
    spot_type = row['type']

In [21]:
row = df.iloc[0]

In [22]:
row['name']

'Brewed Awakening'

In [23]:
df

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,16:30

In [24]:
df_areas

            area_name emoji     lat     lng           area_label
0      Downtown Dubai    🏙️  25.200  55.300    🏙️ Downtown Dubai
1      Jumeirah Beach     🌊  25.205  55.260     🌊 Jumeirah Beach
2        Business Bay     🏢  25.185  55.310       🏢 Business Bay
3           City Walk    🛍️  25.210  55.270         🛍️ City Walk
4             Al Safa     🕌  25.175  55.255            🕌 Al Safa
5   Sheikh Zayed Road     🌆  25.220  55.290  🌆 Sheikh Zayed Road
6                DIFC     🏨  25.215  55.285               🏨 DIFC
7         Zabeel Park     🌳  25.230  55.320        🌳 Zabeel Park
8             Al Wasl     🏫  25.190  55.340            🏫 Al Wasl
9           Oud Metha     🏪  25.240  55.315          🏪 Oud Metha
10        Al Jafiliya     🚇  25.245  55.295        🚇 Al Jafiliya
11        Al Mankhool    🏘️  25.165  55.305       🏘️ Al Mankhool
12            Al Bada     🌴  25.155  55.330            🌴 Al Bada
13              Satwa     🏬  25.175  55.275              🏬 Satwa

In [25]:
import geopy as

SyntaxError: invalid syntax (3451348878.py, line 1)

In [ ]:
from geopy.distance import geodesic

ModuleNotFoundError: No module named 'geopy'

In [ ]:
user_location = (25.155,55.330)
spot1 = (25.213998,55.275438)
round(geodesic(user_location,spot1).km,2)

NameError: name 'geodesic' is not defined

In [ ]:
def calculate_distance(user_location,spot_location):
    dis = round(geodesic(user_location,spot_location).km,2)
    return dis

In [ ]:
def get_distance(row):
    lat = row['lat']
    lng = row['lng']
    spot_location = (lat,lng)
    return calculate_distance(user_location,spot_location)

In [ ]:
row = df.iloc[0]

In [ ]:
row['name']

'Brewed Awakening'

In [ ]:
df['distance'] = df.apply(get_distance,axis=1)

NameError: name 'geodesic' is not defined

In [ ]:
df

,name,lat,lng,type,rating,opening_time,closing_time,is_open_spot
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,Open
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,Open
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,Open
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,Open
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,Open
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,Open
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,Open
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,Open
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,Open
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,Open
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,Open
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,Open
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,Open
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,Open
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,Open
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,Open
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,Open
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,Open
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,Open
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,Open
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,Open
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,Open
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,Open
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,Open
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,Open
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,Closed
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,Open
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,Open
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,Open
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,Open
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,Open
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,Open
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,Open
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,Open
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,Open
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,Closed
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,Open
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,Open
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,Open
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,Open
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,Open
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,Open
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,Open
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,Open
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,Closed
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,Open
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,Open
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,Open
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,Open
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,16:30,Closed

In [ ]:
df

,name,lat,lng,type,rating,opening_time,closing_time,is_open_spot
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,Open
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,Open
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,Open
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,Open
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,Open
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,Open
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,Open
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,Open
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,Open
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,Open
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,Open
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,Open
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,Open
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,Open
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,Open
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,Open
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,Open
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,Open
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,Open
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,Open
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,Open
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,Open
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,Open
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,Open
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,Open
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,Closed
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,Open
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,Open
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,Open
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,Open
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,Open
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,Open
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,Open
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,Open
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,Open
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,Closed
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,Open
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,Open
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,Open
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,Open
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,Open
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,Open
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,Open
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,Open
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,Closed
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,Open
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,Open
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,Open
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,Open
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,16:30,Closed

In [ ]:
opening_time <= 17:55 <= closing_time

SyntaxError: illegal target for annotation (1707973789.py, line 1)

In [ ]:
"07:00" <="17:55"  <= "16:00"

False

In [ ]:
from datetime import datetime
current_time = datetime.now().strftime("%H:%M")

In [ ]:
def is_open_spot(row):
    open_time = row['opening_time']
    close_time = row['closing_time']
    current_time = datetime.now().strftime("%H:%M")

    is_open = open_time <= current_time <= close_time
    if is_open:
        return 'Open'
    else:
        return 'Closed'

In [ ]:
df['is_open_spot'] = df.apply(is_open_spot,axis=1)